-- Insert basic exercises for testing (fixing data types)
INSERT INTO exercises (name, description, exercise_type, exercise_type_detailed, intensity_level, muscle_group_primary, muscle_group_secondary, equipment_required, difficulty_level, instructions, is_approved) VALUES
('Push-ups', 'Classic bodyweight chest exercise', 'strength', 'compound', 'moderate', 'chest', ARRAY['shoulders', 'triceps'], '[]'::jsonb, 'beginner', '["Start in plank position", "Lower chest to ground", "Push back up"]'::jsonb, true),
('Bodyweight Squats', 'Fundamental lower body movement', 'strength', 'compound', 'moderate', 'legs', ARRAY['glutes'], '[]'::jsonb, 'beginner', '["Stand with feet shoulder-width apart", "Lower into squat position", "Return to standing"]'::jsonb, true),
('Plank Hold', 'Core stability exercise', 'strength', 'isometric', 'moderate', 'core', ARRAY[]::text[], '[]'::jsonb, 'beginner', '["Hold plank position", "Keep body straight", "Engage core muscles"]'::jsonb, true),
('Jumping Jacks', 'Cardio warm-up movement', 'cardio', 'dynamic', 'low', 'full_body', ARRAY[]::text[], '[]'::jsonb, 'beginner', '["Jump feet apart while raising arms", "Jump back to starting position"]'::jsonb, true),
('Arm Circles', 'Dynamic shoulder warm-up', 'stretching', 'dynamic', 'low', 'shoulders', ARRAY[]::text[], '[]'::jsonb, 'beginner', '["Extend arms to sides", "Make small circles", "Gradually increase size"]'::jsonb, true),
('Child Pose', 'Relaxing stretch for recovery', 'stretching', 'static', 'low', 'back', ARRAY[]::text[], '[]'::jsonb, 'beginner', '["Kneel and sit back on heels", "Reach arms forward", "Hold and breathe"]'::jsonb, true),
('Burpees', 'Full-body explosive exercise', 'strength', 'compound', 'high', 'full_body', ARRAY['legs', 'core'], '[]'::jsonb, 'intermediate', '["Start standing", "Drop to squat, place hands on ground", "Jump back to plank", "Do push-up", "Jump forward to squat", "Jump up with arms overhead"]'::jsonb, true),
('Mountain Climbers', 'Dynamic core cardio exercise', 'cardio', 'dynamic', 'moderate', 'core', ARRAY['legs'], '[]'::jsonb, 'beginner', '["Start in plank position", "Alternate bringing knees to chest", "Keep core engaged"]'::jsonb, true),
('Lunges', 'Single-leg strength exercise', 'strength', 'compound', 'moderate', 'legs', ARRAY['glutes'], '[]'::jsonb, 'beginner', '["Step forward into lunge", "Lower back knee toward ground", "Push back to starting position"]'::jsonb, true),
('Wall Sit', 'Isometric leg strength exercise', 'strength', 'isometric', 'moderate', 'legs', ARRAY['glutes'], '[]'::jsonb, 'beginner', '["Lean back against wall", "Slide down to 90-degree angle", "Hold position"]'::jsonb, true);