-- Insert basic exercises for testing
INSERT INTO exercises (name, description, exercise_type, exercise_type_detailed, intensity_level, muscle_group_primary, muscle_group_secondary, equipment_required, difficulty_level, instructions, is_approved) VALUES
('Push-ups', 'Classic bodyweight chest exercise', 'strength', 'compound', 'moderate', 'chest', ARRAY['shoulders', 'triceps'], ARRAY[]::text[], 'beginner', ARRAY['Start in plank position', 'Lower chest to ground', 'Push back up'], true),
('Bodyweight Squats', 'Fundamental lower body movement', 'strength', 'compound', 'moderate', 'legs', ARRAY['glutes'], ARRAY[]::text[], 'beginner', ARRAY['Stand with feet shoulder-width apart', 'Lower into squat position', 'Return to standing'], true),
('Plank Hold', 'Core stability exercise', 'strength', 'isometric', 'moderate', 'core', ARRAY[]::text[], ARRAY[]::text[], 'beginner', ARRAY['Hold plank position', 'Keep body straight', 'Engage core muscles'], true),
('Jumping Jacks', 'Cardio warm-up movement', 'cardio', 'dynamic', 'low', 'full_body', ARRAY[]::text[], ARRAY[]::text[], 'beginner', ARRAY['Jump feet apart while raising arms', 'Jump back to starting position'], true),
('Arm Circles', 'Dynamic shoulder warm-up', 'stretching', 'dynamic', 'low', 'shoulders', ARRAY[]::text[], ARRAY[]::text[], 'beginner', ARRAY['Extend arms to sides', 'Make small circles', 'Gradually increase size'], true),
('Child Pose', 'Relaxing stretch for recovery', 'stretching', 'static', 'low', 'back', ARRAY[]::text[], ARRAY[]::text[], 'beginner', ARRAY['Kneel and sit back on heels', 'Reach arms forward', 'Hold and breathe'], true),
('Burpees', 'Full-body explosive exercise', 'strength', 'compound', 'high', 'full_body', ARRAY['legs', 'core'], ARRAY[]::text[], 'intermediate', ARRAY['Start standing', 'Drop to squat, place hands on ground', 'Jump back to plank', 'Do push-up', 'Jump forward to squat', 'Jump up with arms overhead'], true),
('Mountain Climbers', 'Dynamic core cardio exercise', 'cardio', 'dynamic', 'moderate', 'core', ARRAY['legs'], ARRAY[]::text[], 'beginner', ARRAY['Start in plank position', 'Alternate bringing knees to chest', 'Keep core engaged'], true),
('Lunges', 'Single-leg strength exercise', 'strength', 'compound', 'moderate', 'legs', ARRAY['glutes'], ARRAY[]::text[], 'beginner', ARRAY['Step forward into lunge', 'Lower back knee toward ground', 'Push back to starting position'], true),
('Wall Sit', 'Isometric leg strength exercise', 'strength', 'isometric', 'moderate', 'legs', ARRAY['glutes'], ARRAY[]::text[], 'beginner', ARRAY['Lean back against wall', 'Slide down to 90-degree angle', 'Hold position'], true);