// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmfqvowxountmfhiwbsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZnF2b3d4b3VudG1maGl3YnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzQyMjUsImV4cCI6MjA2OTUxMDIyNX0.voGXPpGDN8Fz5Vky96prlZwWKDrYQKfLY5hbb8upEFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});